version: "3.9"

services:
  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_server
    environment:
      - SA_PASSWORD=Goldie25!
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
